language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3

install: "sudo apt-get -qq install libfreetype6-dev liblcms2-dev libwebp-dev ghostscript"

script:
  - python setup.py clean
  - python setup.py build_ext --inplace
  - python selftest.py
  - python Tests/run.py
